### ISSUE TITLE
bug: Fix warning - Received `true` for a non-boolean attribute `isalternate`

### ISSUE THREAD

**Issue by JessicaF** [devsoc-unsw/freerooms#459]
When running the frontend, a warning in the terminal is shown: 
```
Warning: Received `true` for a non-boolean attribute `isalternate`.
```

**Comment by SkellyBG** [comment]
while looking at nextjs bundle analyze, I spent sometime digging and fixed this error ^^

**Comment by JessicaF** [comment]
@SkellyBG Thanks for looking into this! 🙌 Did you end up making a PR with a workaround? How did you end up fixing it?

**Comment by SkellyBG** [comment]
I haven't made a PR yet - the change still live in another branch that I was using to try speeding up `next dev`: https://github.com/devsoc-unsw/freerooms/compare/dev...skelly/idk-what-im-doing#diff-3b4a40a8d1dac988639aaef4828e986d6cf8997db36925d90d882c3ce5134d68R71-R78

I'll split the change to a different branch and make a PR for it ^^

**Comment by JessicaF** [comment]
@SkellyBG Hahaha the branch and commit names 🤣🤣 But yes please split it into a different branch following the naming conventions and make a PR when ready 😊 

Much appreciate you taking the initiative to make improvements!
