### ISSUE TITLE
feature: Add a back button from room page to building room list

### ISSUE THREAD

**Issue by JessicaF** [devsoc-unsw/freerooms#464]
When accessing this page (on both laptop and mobile), add a back button so users can navigate back to the building list or whatever the previous page was. 
- Flexible with the design as long as it looks nice (good starting point is probably somewhere top left (maybe add a left arrow symbol with the words BACK)

![Image](https://github.com/devsoc-unsw/freerooms/assets/54833118/1b1c5e35-6250-4b2a-bef7-188adbf82dd7)

 This page can be accessed after you click on a room from the list of rooms a building has:

![Image](https://github.com/devsoc-unsw/freerooms/assets/54833118/2dc9813a-ead4-4d33-ad73-dc41ed6217f6)

**Comment by kellysu1** [comment]
I added what i think is the back button that opens the drawer as well but i cannot say for sure cause my localhost doesnt work. I am not sure why the lint and build is like that cause i used the lint thing on my local and it says its fine...
