### ISSUE TITLE
feature: Make time selection modal look better

### ISSUE THREAD

**Issue by JessicaF** [devsoc-unsw/freerooms#465]
Make this pop-up look better (make sure to consider both mobile and laptop view) 
- Cancel and Ok buttons could be better positioned and designed
- The pencil icon should be clearer and more obvious on its functionality
- "Select time" text is rather small
- The second image shows what happens when you click on the pencil icon - this screen can also be redesigned to reduce padding and make the clock symbol and buttons look nicer

![Image](https://github.com/devsoc-unsw/freerooms/assets/54833118/0be97bd3-b2e8-4c30-a616-3b06fa9fa459)
![Image](https://github.com/devsoc-unsw/freerooms/assets/54833118/8ae57cd6-4f48-422c-a0d1-25b617265614)

**Comment by francojreyes** [comment]
can you pls pls pls move it out of the sidebar (maybe where the search is rn)
