### ISSUE TITLE
feature: Room block that displays static information

### ISSUE THREAD

**Issue by TimezDed** [devsoc-unsw/freerooms#503]
### Requirements
- Displays static information - room name + availability details
- When you click on room block, should navigate to the corresponding room page
- When there are multiple blocks on the page, ensure that scrolling behaviour is defined

![image](https://github.com/user-attachments/assets/a58681c8-4e9e-4bc0-bc21-0ad0613ee3ee)

**Comment by marktran2** [comment]
can reuse the `RoomAvailabilityBox` component for this task (no need to reinvent the wheel)

contract ensures that backend will handle the data returned is relevant to filter input
